### ISSUE TITLE
redis API compatibility

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#117]
A very big project, need update whole db.

every key must save key -> type in db, although it may hit a little performance, it is worth to do it. 

maybe add a compile option to support this, if someone don't like this feature, he can disable it?

**Comment by spitfire2** [comment]
any progress of this? Redis compatibility is very important for us.

**Comment by siddontang** [comment]
@spitfire2  you can try [qdb](https://github.com/reborndb/qdb), this is a redis compatibility implementation.

**Comment by GlenDC** [comment]
I'm not sure if it's related. But there are quite some commands supported by Redis that aren't supported by Ledis. Would it be in the scope of this project, to support a lot more of the available redis commands?

I do think that Ledis covers the most important commands, and have not yet run into a problem where I was missing a command that I have in Redis but not in Ledis. But perhaps it could be interesting to list which commands are missing, and describe how do-able adding each command would be.

What do you think @siddontang?

**Comment by siddontang** [comment]
Hi @GlenDC 

LedisDB is not compatible with Redis, but if we need commands, we can think a way to add them one by one.

**Comment by popadi** [comment]
Is there a way to get all the keys using a regex/pattern? In Redis, there is the KEYS function that does that and I am wondering if the same behaviour can be obtained using LedisDB. Right now, using the redis client connected to a ledisdb instance gives an error:

```
client.keys("domain*", function (err, res) {
    console.log(err, res);
});
```
=>
```
{ ReplyError: command not found
    at parseError (/home/adrianpop/test/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/adrianpop/test/node_modules/redis-parser/lib/parser.js:303:14) command: 'KEYS', args: [ 'domains*' ] }
```

Thanks!
