### ISSUE TITLE
refactor scan command

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#138]
Now "scan" commands are very redundant and complicate, see #137. It is time to refactor them. 

For compatibility, I may not remove old `XSCAN`, `XLSCAN`, etc..., so maybe another API is better, like this:

```
XKEYSCAN type cursor [MATCH match] [COUNT count]
```

"type" is kv, list, hash, set, and zset. This API likes redis [SCAN](http://redis.io/commands/scan), to iterates keys, for different data type. 

But if we don't care compatibility, we may use `XSCAN` instead, @pkieltyka. 

```
XHSCAN key cursor [MATCH match] [COUNT count]
```

XHSCAN likes redis HSCAN to iterates hash field and values. 

```
XSSCAN key cursor [MATCH match] [COUNT count]
```

XSSCAN likes redis SSCAN to iterates set memebers.

```
XZSCAN key cursor [MATCH match] [COUNT count]
```

XZSCAN likes redis ZSCAN to iterates zset element and score.

**Comment by pkieltyka** [comment]
Good stuff! I don't think backwards compatibility for these kinds of commands matter. 

Also, what do you think about the naming of `XHSCAN` instead of `HXSCAN` ? I like the idea of prefixing any "extensions" to redis commands with an `X`.. makes for more consistency.

**Comment by siddontang** [comment]
Aha, @kouhate suggests me to prefix data type for commands like Redis. I think using `X` prefix may be good to distinguish Redis commands. 

Maybe we can think another name, like `HSEEK`?

**Comment by kouhate** [comment]
Hi there, OK. I agree to use <code>X</code> prefix.

I think <code>H</code> <code>S</code> <code>Z</code> prefix makes the target data type more certain..., but this may disturb the consistency.

**Comment by siddontang** [comment]
Hi @kouhate,  Support in develop branch now. Commands:

```
XSCAN type cursor [MATCH match] [COUNT count]
XHSCAN key cursor [MATCH match] [COUNT count]
XSSCAN key cursor [MATCH match] [COUNT count]
XZSCAN key cursor [MATCH match] [COUNT count]
```

**Comment by kouhate** [comment]
Thanks @siddontang, I'll test them later.

**Comment by kouhate** [comment]
Hi @siddontang, would you also support reverse scan?

As I know reverse scan is more slower than forward one, but this may useful for some use case.

Maybe <code>XREV..</code> bring more redundancy like before, so if you could, supporting by option would be better.
<code>XSCAN type cursor [MATCH match] [COUNT count] [ASC | DESC]</code>

**Comment by siddontang** [comment]
Hi @kouhate , redis does not support reverse scan, and I don't find a useful use case too.

Btw, supporting reverse scan is easy, is it necessary to support reverse scan for hash, set and zset?

**Comment by kouhate** [comment]
@siddontang, especially for hash, reverse scan is necessary I think.

In my use case, Hash filed-name will TimeUUID and I want to retrieve recent data.
For time series data,  maybe reverse scan cannot be avoided, or app must plan the key name to be reversed.

In the case of Cassandra CQL3, they support <code>WITH CLUSTERING ORDER BY (clumn-name [ASC | DESC])</code> option for setting default order.
Once the table are created with the option, saved data is always ordered by the specified order.
So, the performance of reverse heavy operation will be boosted after setting the DESC option.

Furthermore, ZSET also have a similar problem.
For ranking or access counting, what we are interested in is usually the highest score data.
So, we easily use reverse scan such as ZREVRANGE or ZREVRANGEBYSCORE, but unfortunately, these commands are 10 times slower than forward scan, especially using leveldb or rocksdb as storage.
This is not happend when using Redis.

In my app, sometimes a score of ZSET is prefixed by "-" on purpose of reverse sorting, but this force me to decode and encode when inserting and retrieving.

Anyway, reverse scan is necessary for my use case.

**Comment by siddontang** [comment]
@kouhate , I will add reverse scan later, but you must know below:

+ reverse scan is slower than forward, unless leveldb or rocksdb improves it.
+ migrating a huge hash data (with many fields and values) is very terrible in xcodis when resharding. We must dump this huge data first, then transfer into another server and load it, it may take huge memory, cost many time and block other write operations for a long time. 

Btw, I think ZREVRANGE* may be more convenient than XZSCAN DESC.

**Comment by kouhate** [comment]
@siddontang, ok, I know the two cons, but does XMIGRATEDB keep blocking any write operation until  finished?

If so, it may be a fatal problem for me.

**Comment by siddontang** [comment]
Now, yes, because I must guarantee the atomic migration. When I migrate the key, other write operation may update the key at same time, it may cause data inconsistency. 

But this can be improved later, only using a lock for the key and not for the whole.

**Comment by siddontang** [comment]
@kouhate , for redis, scan can not guarantee the return key order, the same for ledisdb. e.g. for hash, the key saved in ledisdb like this `db(1 byte):hash tag(1 byte):key length(2 byte, big endian):key`, so the key with short size will be scanned first. If the two key have same size, we will use lexicographical ordering. 

So I think you should have the same size for your hash field if you want to scan them with ASC or DESC. 

Btw, for redis, ZSCAN first scans elements with small score, then uses lexicographical ordering for same score, but for ledisdb, it only use lexicographical ordering, is this a problem for you?

**Comment by kouhate** [comment]
Hi @siddontang, those difference is not a problem.
My purpose of using *XSCAN is to scan by value, so this is rather welcomed.

**Comment by siddontang** [comment]
Hi @kouhate, I have been trying to use ledisdb + xcodis + redis-failover to build a high availability distributed key-value store service in my company.  I guess you may do the similar thing. 

Could you tell me your email? Maybe we can have a in-depth discussion or even work together to build a NoSQL product.

**Comment by kouhate** [comment]
Hi @siddontang, I've just updated my prof, pls check it.
