### ISSUE TITLE
Restriction on set? compared to Redis

### ISSUE THREAD

**Issue by adulau** [ledisdb/ledisdb#147]
A small question, what are the restriction of a set compared to a "standard" Redis?

After inserting elements in a set after a lot of inserts, I got the following error:

"invalid set member size"

The cardinality of the set is 0 and doesn't seem related to set itself.

Thank you 

```
# Server
os:linux
process_id:49472
addr:127.0.0.1:6380
http_addr:127.0.0.1:11181
readonly:false  
goroutine_num:13
cgo_call_num:1106462367
resp_client_num:1

# Store
name:leveldb
get:310198512
get_missing:3
put:310183483
delete:30010
get_total_time:2h7m23.712650466s
iter:45641
iter_seek:2388600
iter_close:45640
batch_commit:155101750
batch_commit_total_time:1h2m56.655445368s

# Mem
mem_alloc:1.592M
mem_sys:18.139M
mem_looksups:8.139K
mem_mallocs:1.414G
mem_frees:1.414G
mem_total:40.586G
mem_heap_alloc:1.592M
mem_heap_sys:12.266M
mem_head_idle:10.086M
mem_head_inuse:2.180M
mem_head_released:8.430M
mem_head_objects:12448

# GC
gc_last_time:2015/03/13 19:24:32.736
gc_num:26181
gc_pause_total:26.544528157s
gc_pause_history:1.331656ms,1.957258ms,1.000541ms,619.643µs,1.033968ms

# Replication
role:master
pub_log_num:0
pub_log_ack_per_time:0
slaveof:
last_log_id:0
first_log_id:0
commit_log_id:0
master_last_log_id:0

```

**Comment by siddontang** [comment]
Hi @adulau, now the ledisdb maximum set memeber size is 1024, you can not insert larger one.
I know redis supports 512mb,  but I don't want to support so large member for performance.

We may change maximum set member below. 

```
//max set member size
MaxSetMemberSize int = 1024
```

Because I use 2 byte to store member size in backend storage, so the maximum size is 65535.
I would change  MaxSetMemberSize to a larger one, which is enough for many projects, maybe 10240?

**Comment by xyproto** [comment]
Could the maximum set size be doubled when it runs out of space, until it reaches maximum size? This way, people using small sets will have good performance and people using larger sets will not get an error?

**Comment by siddontang** [comment]
Sorry that I forgot to enlarge this value for current release version. I will change this to a large value(maybe 1GB, like KV type) later. 

For redis, the maximum value size is 512MB, and I think it's ok for most of us.Supporting too large value is not necessary.
