### ISSUE TITLE
support config set 

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#152]

**Comment by ericnp** [comment]
+1, this would be very useful to me. And/or RESP 'SHUTDOWN' command

**Comment by siddontang** [comment]
@ericnp, Any contribution is very welcome. :smile: 

I will support `SHUTDOWN` later.

**Comment by siddontang** [comment]
Hi @ericnp , SHUTDOWN is supported now.

I guess you want to change data_dir in runtime, this may be dangerous for ledis, because we need to handle lots of thing, like close storage or replication first, etc..... So `config set` is not proper for this.

**Comment by ericnp** [comment]
Oh, damn, I missed notifications that you responded! That's awesome, thanks so much.

**Comment by ericnp** [comment]
I'd like to work on the project if you could use my help. Which of the Issues are high priority that I could work on?

**Comment by siddontang** [comment]
Thanks @ericnp 

You can contact me directly later, or in the github issue too. 

+ Gmail: siddontang@gmail.com
+ Skype: live:siddontang_1
