### ISSUE TITLE
In the use of these interfaces to add the code, the application will be smaller

### ISSUE THREAD

**Issue by Leither** [ledisdb/ledisdb#156]
```
//_ "github.com/siddontang/ledisdb/store/boltdb"
_ "github.com/siddontang/ledisdb/store/goleveldb"
_ "github.com/siddontang/ledisdb/store/leveldb"
//_ "github.com/siddontang/ledisdb/store/mdb"
//_ "github.com/siddontang/ledisdb/store/rocksdb"
```

In the use of these interfaces to add the code, the application will be smaller

**Comment by siddontang** [comment]
@Leither ledis will use goleveldb and boltdb for default, and use go build tags for other storages, if you don't build with passing rocksdb, leveldb or lmdb tags, ledis will not build them. 

Later I will check whether build with not passing these flags will reduce the application size.

**Comment by siddontang** [comment]
@Leither , in my mac osx, I do like yours above, but the application size reduces little.
