### ISSUE TITLE
support for sophia key-value storage 

### ISSUE THREAD

**Issue by uchti** [ledisdb/ledisdb#160]
Please add support  sophia v1.2 ( http://sphia.org/ ) key-value storage for liedisdb.  
Thank you for ledisdb.

**Comment by siddontang** [comment]
Hi @uchti 

Could you tell me why do you want to use sophia? Do LevelDB, RocksDB, LMDB or others not fit your need?
I don't use sophia before, is its performance better than others? Has it some killer features?

**Comment by uchti** [comment]
Leveldb, RocksDB (LSM tree) have problems to get value on very large volumes of data when data stored on deeper level, sophia does not have such problems.
