### ISSUE TITLE
List will eventually exceed listMaxSeq even if we do an lpop for every rpush

### ISSUE THREAD

**Issue by ericnp** [ledisdb/ledisdb#162]
At which point the data in the backend would have to be manually "renormalized" in order to repair? And likewise for listMinSeq/lpush/rpop.

Or am I mistaken?

**Comment by siddontang** [comment]
Yes, this may be a danger, but I have not found a better way to solve it. Maybe later we can use a int64 for the list head and tail sequence, so it is nearly impossible that the list will exceed. 

But this will let old user upgrade saved data.
