### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by techtonik** [ledisdb/ledisdb#164]
I needed an alternative to Redis that works on Windows.Can LegisDB be such replacement?

**Comment by siddontang** [comment]
LedisDB is written with go, and you can use a pure go backend storage like boltdb or goleveldb, so I think you can use it in windows. Btw, I have no windows environment so I can not tell you whether it is or not. 

LedisDB is not redis, with some differences, you must know that too.

**Comment by techtonik** [comment]
But LegisDB is API compatible with Redis, no?

I tried to use LegisDB from repository, but build uses bash scripts. Is it possible to have a cross-platform build toolchain?

**Comment by siddontang** [comment]
Not fully compatible with Redis.

The build sciripts is only for linux and macosx, you can use `go install ./...` directly for pure go version.  :-)

**Comment by techtonik** [comment]
My goal is basically to get http://python-rq.org/ working on Windows. I don't know what protocol does it use to talk with Redis, but I hope it is not as hard as getting Redis there.

To build LedisDB I tried:
```
> set GOPATH=C:\ledis
> go get github.com/tools/godep
> go install ./...
cmd\ledis-benchmark\main.go:13:2: cannot find package "github.com/siddontang/goredis" in any of:
	C:\Program Files\Go\src\github.com\siddontang\goredis (from $GOROOT)
...
```
And a lot of messages like this. What else is needed?

**Comment by siddontang** [comment]
You may use `godep go install ./...`

**Comment by techtonik** [comment]
It appears that no, can't use it. =)
```
>godep go install ./...
'godep' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by siddontang** [comment]
The godep will be installed in $GOPATH/bin, you must set this in your system $PATH or call godep with absolute command path like `$GOPATH/bin/godep`

**Comment by techtonik** [comment]
Ok. For Windows it is:
```
> %GOPATH%\bin\godep go install ./...
# github.com/siddontang/ledisdb/server
server\client_resp.go:175: undefined: syscall.Kill
godep: go exit status 2
```
Still no luck.

**Comment by siddontang** [comment]
Bad  news, windows has no this function. 

You can first comment this line which has no affect. :-)

**Comment by techtonik** [comment]
```
# github.com/siddontang/ledisdb/server
server\client_resp.go:11: imported and not used: "syscall"
```
Commented import too. Now `godep` worked well. Is that all?

**Comment by techtonik** [comment]
```
> %GOPATH%\bin\ledis-cli.exe 
Please use linenoise to build again, or use redis-cli instead
```
Hmm...

**Comment by siddontang** [comment]
You can not build ledis-cli in windows, the same for redis-cli too, because they both use a linenoise lib which only be supported in linux and macosx.

**Comment by techtonik** [comment]
=/

How to test that it works then?

**Comment by siddontang** [comment]
Pardon? I don't know what you mean?

I know that MS builds a portable redis version in windows, maybe including a redis-cli?

**Comment by techtonik** [comment]
I mean how can I test that `ledisdb` is compiled successfully and works as expected?

**Comment by siddontang** [comment]
maybe:

+ https://github.com/MSOpenTech/redis, build it and use redis-cli.exe for test
+ https://github.com/ServiceStack/redis-windows/tree/master/src/msopentech/redis-64.2.8.17, it has a redis-cli.exe, but I don't know whether it is ok or not in your system
+ write your own test with official redis library, like python, go, but it costs time.

**Comment by techtonik** [comment]
Strange that there is no Go client to test access to `ledisdb` from different machines. May be later.

**Comment by lunny** [comment]
Closed since we moved to go mod.
