### ISSUE TITLE
what about backend storage on mysql? over handlersocket or plain sql :) ///∞

### ISSUE THREAD

**Issue by blinkinglight** [ledisdb/ledisdb#165]

**Comment by siddontang** [comment]
Hi @spx, I just want to let ledisdb keep simple and don't rely on outer service like MySQL. 

If MySQL is down, all services will not work too and I don't think using MySQL is faster than other local backend storage like RocksDB, but we need a benchmark for it. :-)

Btw, supporting MySQL may be easy (I prefer plain sql and don't trust handlersocket) but I have no time now, sorry.
