### ISSUE TITLE
[Question] How to "Easy to embed in Go application"

### ISSUE THREAD

**Issue by txchen** [ledisdb/ledisdb#168]
This is in feature list, however I cannot find wiki or doc or example showing how to do that. Could you please shed some light? Thanks a lot!

**Comment by siddontang** [comment]
```
import "github.com/siddontang/ledisdb/ledis"
 l, _ := ledis.Open(cfg)
db, _ := l.Select(0)

db.Set(key, value)
db.Get(key)
```

a simple example. :-)

**Comment by txchen** [comment]
thanks, will have a try!
