### ISSUE TITLE
No api HEXISTS

### ISSUE THREAD

**Issue by Leither** [ledisdb/ledisdb#170]
like Redis
 http://redisdoc.com/hash/hexists.html

**Comment by siddontang** [comment]
I have already supported it. maybe another API?

**Comment by Leither** [comment]
http://godoc.org/github.com/siddontang/ledisdb/ledis
no hexists

HKeyExists :key
HEXISTS : key and field

**Comment by mmindenhall** [comment]
@Leither is correct...there does not appear to be an implementation for HEXISTS, despite it being in the list of [supported commands](https://github.com/siddontang/ledisdb/wiki/Commands#hexists-key-field).  Currently, the only way to determine whether a field exists within a hash is to fetch it via HGET:

```go
	myObj, err := ledisdb.HGet(myKey, myField)
	if err != nil {
		// handle error
	}
	if myObj == nil {
		// does not exist
	} else {
		// exists
	}
```

I'd much rather just do this:

```go
	if ledisdb.HExists(myKey, myField) {
		// exists
	} else {
		// does not exist
	}
```

**Comment by siddontang** [comment]
@mmindenhall 
Could you send me a PR to support it?

**Comment by lunny** [comment]
I think this has been implemented. See https://github.com/ledisdb/ledisdb/blob/master/server/cmd_hash.go#L310 . I will close this now and feel free to reopen it.
