### ISSUE TITLE
remove lua script support

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#174]

**Comment by felixbuenemann** [comment]
Why do you want to remove it?

**Comment by siddontang** [comment]
We cannot support whole lua features like redis, btw, using lua in go has some limitations and we have to distinguish 5.1, 5.2 or even 5.3 later.

**Comment by felixbuenemann** [comment]
If you don't want to support multiple lua versions, you could just specify the supported version in the README or vendor the lua sources [like redis](https://github.com/antirez/redis/tree/unstable/deps/lua) which also uses lua 5.1.

Even if not all features possible in redis work in ledis, I think it's still a useful feature to have.
