### ISSUE TITLE
remove boltdb and lmdb, may only support leveldb/rocksdb/goleveldb

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#175]

**Comment by holys** [comment]
:+1:

**Comment by pkieltyka** [comment]
why remove boltdb..?

**Comment by siddontang** [comment]
well, @pkieltyka , the newest boltdb may cause a deadlock, which it doesn't allow run both read and write transaction in a goroutine at same time, but in LedisDb, we have many places to do these things:

```
it := db.NewIterator()
defer it.Close()

//iteration and use db.Delete to do something. 
``` 

This is ok with goleveldb/rocksdb/leveldb, and even lmdb, but not boltdb now. 
I have no time to fix this for boltdb now and I don't think its performance can beat rocksdb, maybe the best choice is to remove it.

If someone tells me they will use it in production, I may consider fixing it. 

Btw, I find a way to let rocksdb support transaction too, so later I can support `begin`, `commit`, `rollback` feature with rocksdb/leveldb/goleveldb. :-)

**Comment by zaibon** [comment]
Is boltdb already removed from the supported backend ?
```
ledis-server -db_name boltdb    
no config set, using default config
store boltdb is not registered
```

**Comment by siddontang** [comment]
yes, the newest boltdb version will cause deadlock and I have no way to fix it now.

**Comment by mmindenhall** [comment]
Just saw this...I'm using boltdb in the application I'm currently building.  Planning to be in production with it in a few weeks.

I guess I'm confused about why you need separate transactions?  The boltdb readme says "Each transaction has a consistent view of the data as it existed when the transaction started.".  So it would seem that if you created a single read-write transation, you could both iterate and delete (per the comment above from Aug 7).  I assume I'm missing something here, so please let me know what the fix would entail.

**Comment by siddontang** [comment]
@mmindenhall 
If boltdb starts a read only transaction, it will block any other write operations, and even more, if we do some write operations in read transaction, a deadlock occurs.

Now the iterator implementation based on boltdb uses its read only transaction, and we do some write operations in some iterations, like
```
it := SeekFirst()
defer it.Close()

for it.Next() {
    key := it.Key()
    deleteKey(key)
}
```
we will meet deadlock using boltdb. We can solve this problem with refactoring all these codes, but I have no time to do it, sorry.

**Comment by lunny** [comment]
I think we should make an interface and users could implement their backend.

**Comment by lunny** [comment]
Closed since it has been done.
