### ISSUE TITLE
Config questions

### ISSUE THREAD

**Issue by pkieltyka** [ledisdb/ledisdb#178]
What are these config options for:

https://github.com/siddontang/ledisdb/blob/master/etc/ledis.conf#L42-L46

https://github.com/siddontang/ledisdb/blob/master/etc/ledis.conf#L145-L149

perhaps we can write more about some of the important ones in a doc?

thanks.

**Comment by siddontang** [comment]
@pkieltyka 

the first one is to control leveldb/rocksdb  synchronous writes, leveldb/rocksdb uses asynchronous writes default, we can use this config to let it how to do a synchronous write.

the second one is to control replication log how to be flushed to disk. 

I will add some docs later.
