### ISSUE TITLE
Benchmarking with GolevelDB

### ISSUE THREAD

**Issue by darshan-ghumare** [ledisdb/ledisdb#179]
Hi,

I have a Ubuntu 14.04 with 32 GB RAM and Quad core Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz machine.
Following is the performance I am getting on 10GB HDD,

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set"
set: 2.070735167s 2070.735 micros/op, 482.92op/s

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set" -n=1000
set: 2.072011707s 2072.011 micros/op, 482.62op/s

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set" -n=3000
set: 10.235436495s 3411.812 micros/op, 293.10op/s

Is this expected or is it slow?

Thanks,
Darshan

**Comment by siddontang** [comment]
Seem a little slow, how about use smaller size like 1k or with rocksdb/leveldb?

**Comment by darshan-ghumare** [comment]
With RocksDB

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set"
set: 51.073598ms 51.073 micros/op, 19579.59op/s

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set" -n=3000
-bash: root/prototypes/ledisdb/bin/ledis-benchmark: No such file or directory
root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=4096 -t="set" -n=3000
set: 118.286611ms 39.429 micros/op, 25362.13op/s

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=8192 -t="set" -n=3000
set: 139.347168ms 46.449 micros/op, 21528.96op/s

root@Machine3:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb# /root/prototypes/ledisdb/bin/ledis-benchmark -port=6380 -vsize=65536 -t="set" -n=3000

set: 1m3.72185611s 21240.619 micros/op, 47.08op/s


Is it possible to get 10K IOPS for value size from 4K to 128K?

**Comment by siddontang** [comment]
128k seems too large. 4k seems having an acceptable performance. 

I don't know why goleveldb has the terrible performance, I will check it again and contact the author. 

What's your scenario for data saving, if you have lots of data with big size (64k or 128k), I don't think ledisdb can fit your need. 

Thank you.

**Comment by darshan-ghumare** [comment]
Following is my setup,

   1. FIO with following parameters, ioengine=psync, iodepth=32, bs=4k,
   number_ios=1000000, rw=randwrite, direct=1, fsync_on_close=1
   2. Runs FIO on Ubuntu 14.04 VM created on QEMU-KVM.
   3. I have written QEMU block driver which will trap FIO IOs on disk and
   forward it to LedisDB using hiredis APIs.

Following are my observations,

   1. With 4K block size I got 5.4K IOPS.
   2. With 8Kblock size I got 3K IOPS.
   3. IOPS this way drops down to 1-3 IOPS when I start increasing block
   size eventually.

Please help.


On Mon, Aug 24, 2015 at 9:27 AM, siddontang <notifications@github.com>
wrote:

> 128k seems too large. 4k seems having an acceptable performance.
>
> I don't know why goleveldb has the terrible performance, I will check it
> again and contact the author.
>
> What's your scenario for data saving, if you have lots of data with big
> size (64k or 128k), I don't think ledisdb can fit your need.
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siddontang/ledisdb/issues/179#issuecomment-134015709>.
>



-- 
Darshan®

**Comment by siddontang** [comment]
Sorry that I don't know how to tune the IO.
I see that you use hiredis APIs, do you use multi connections concurrently at same time, if you just only use one client, the performance is not good.
