### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by xpurer** [ledisdb/ledisdb#186]
godep go install -tags '' ./...
# github.com/siddontang/ledisdb/rpl

rpl/log.go:45: undefined: sync.Pool
# github.com/ugorji/go/codec

Godeps/_workspace/src/github.com/ugorji/go/codec/encode.go:533: undefined: sync.Pool
Godeps/_workspace/src/github.com/ugorji/go/codec/encode.go:1219: undefined: sync.Pool
godep: go exit status 2
Makefile:17: recipe for target 'build' failed
make: **\* [build] Error 1

**Comment by siddontang** [comment]
What's your go version? or do you set your GOROOT, GOPATH correctly?

**Comment by luren5** [comment]
@siddontang 我也遇到了同样的问题

**Comment by lunny** [comment]
Now we use go mod.
