### ISSUE TITLE
Compare to SSDB

### ISSUE THREAD

**Issue by ketor** [ledisdb/ledisdb#187]
Our team is looking for a ondisk redis db now.
We test SSDB for a long time but today I find ledisdb.

After looking into the wiki of ledisdb, I can not easily find out what is the key difference between ledisdb and SSDB.

So would please tell me something about it?

Thanks!

**Comment by siddontang** [comment]
LedisDB is Go and SSDB is C++, I think this may be the biggest difference. :-)

Most of these projects (not only LedisDB, SSDB, but also RebornDB, etc...) all use a fast key/value store like LevelDB or RocksDB as the backend storage, and use the similar way to emulate Redis's APIs.

**Comment by ketor** [comment]
Thank you for reply.

What I focus on is the Redis protocol compatibility between SSDB and ledisdb. Because many redis db instances will migrate to disk db like ledisdb or SSDB, and I am researching redis disk db choices.When I find ledisdb, I feel incredible. But it is hard to see if there is a clear evaluation criteria between SSDB and ledisdb.

If you could able to explain more about the Redis protocol  compatibility between SSDB?

**Comment by siddontang** [comment]
There is no big different in inner implementation to support Redis APIs for LedisDB and SSDB. 
Why I want to develop LedisDB but not use SSDB is that SSDB is not supported cluster, and SSDB is written by C++, which is hard to modify, at the same time, SSDB saves operation log in LevelDB for replication which I don't think it is efficient. 

LedisDB is written by Go, so you can learn it, modify it easily, some people who don't know Go can even send me a PR to improve it.
Using xcodis(a modified codis verion), LedisDB can support cluster.
And I refer MySQL binlog to support LedisDB's replication. 
I think above is the biggest different. 

Btw, Go is not slower than C++, if you care much about performance, use SSDB. :-)
