### ISSUE TITLE
slave node error when execute flushall command on master node

### ISSUE THREAD

**Issue by FlamingTree** [ledisdb/ledisdb#194]
when execute "flushall" command on master, slave node repeatly log error like this:
[2015/10/24 19:45:39] 127.0.0.1:58183 "sync 3" 0 [invalid sync logid 3 > 0 + 1]

**Comment by FlamingTree** [comment]
https://github.com/siddontang/ledisdb/blob/master/ledis/ledis.go#L174-L179  here is problem, flushall clear commit id and logid, but slave node doesn't clear. is it known problem?

**Comment by siddontang** [comment]
hi @FlamingTree , as I knew, if the sync failed, slave will try another full sync later, if not, this may be a problem. 

of you can send slaveof instead to fix it?

**Comment by FlamingTree** [comment]
I read flushall command implementation, found it does not log deletion write, nor send flushall command to slave, but it clean master's logid, cause master's logid less than slave's. maybe better solution is send flushall to slave, but i don't know how to~

**Comment by FlamingTree** [comment]
https://github.com/FlamingTree/ledisdb/commit/f781c8e9d8fd088c2fc7d96ae39a7713130be86e  I try to fix it. I will send a PR if it's ok. but it's insignificant because rarely use.
