### ISSUE TITLE
为什么要去除掉lmdb？

### ISSUE THREAD

**Issue by wangfx** [ledisdb/ledisdb#200]
0.5版本还支持lmdb吗？ 删除lmdb基于什么原因？ 其实我想使用lmdb 的range*功能，levedb，rocksdb range 特别是倒序效率太低，lmdb相对leveldb和rocksdb性能波动性要平稳的多，levedb和rocksdb文件合并的时候，查询效率会很低

**Comment by wangfx** [comment]
我想基于levedb开发个分布式数据库，是这么想的：
1、主要使用rocksdb存储kv
2、只要使用lmdb存储zset
有规律的生成key，避免rocksdb深度排序，key值生成的想法如下：
xxxx00111nxa1234567
xxxx 每十天一个计数的时间值
00  集群标示，最大3844
111 slot数最大1000，用于数据迁移，每个集群主机数,最大1000
n   一级命名空间分类 最大62
x   二级命名空间分类 最大62
a   数据类型
1234567  基于xxxx00111n生成key序列号

这样避免rocksdb深度排序，利用lmdb的zset的range*性能，lmdb相当于一个rocksdb的索引库；
请指教！！！

**Comment by siddontang** [comment]
lmdb没有删除，只删除了boltdb。不过lmdb现在需要传入lmdb这个building tag进行编译，使用 make build_lmdb即可。
