### ISSUE TITLE
[Request] Benchmark on space efficiency of different backends

### ISSUE THREAD

**Issue by dg3feiko** [ledisdb/ledisdb#207]
Thank u @siddontang for such nice wrapper of nosql db engines, our team love it so much. 

As you have run benchmarks on IO performance of different backends, we'd also love to see the space efficiency of them as we cares a lot about ram and disk space usage of them. Could u please make such tests and publish it for everyone as better reference of making choices on backend ?

**Comment by siddontang** [comment]
Hi @dg3feiko 
Thanks for you attention, but now I have not time to do this (have to do lots of works for my job :cry: ), sorry. 
I will add it TODO.
