### ISSUE TITLE
LSet not support

### ISSUE THREAD

**Issue by Leither** [ledisdb/ledisdb#208]
rt

**Comment by Leither** [comment]
func (db *DB) LSet(key []byte, index int32, value []byte) error {
	if err := checkKeySize(key); err != nil {
		return err
	}

	var seq int32
	var headSeq int32
	var tailSeq int32
	//var size int32
	var err error
	t := db.listBatch
	t.Lock()
	defer t.Unlock()
	metaKey := db.lEncodeMetaKey(key)

	headSeq, tailSeq, _, err = db.lGetMeta(nil, metaKey)
	if err != nil {
		return err
	}

	if index >= 0 {
		seq = headSeq + index
	} else {
		seq = tailSeq + index + 1
	}

	sk := db.lEncodeListKey(key, seq)
	//找到了对应的key sk
	//v := it.Find(sk)
	//fmt.Printf("LSet sk=%d\r\n", sk)
	t.Put(sk, value)
	err = t.Commit()
	return err
}

**Comment by siddontang** [comment]
@Leither Could you send me a PR directly. 
Sorry for replying late. :-)
