### ISSUE TITLE
score只支持整型感觉很受限制，很多排序算法算出的值都是float64，直接转成整型又感觉变成了大数...

### ISSUE THREAD

**Issue by insionng** [ledisdb/ledisdb#211]

**Comment by siddontang** [comment]
score这个是历史遗留原因了，当时没想到什么很好的办法对float进行排序。
不过虽然现在有办法了，但是如何处理遗留数据又是一个问题，而且没时间弄，就一直放着了。

float排序编码可以参考 https://github.com/reborndb/qdb/blob/master/pkg/store/util.go

**Comment by insionng** [comment]
如果能不考虑遗留数据（我打算对旧的排序数据重置），那么应该针对ledisdb哪里进行改动才能支持float64？

或者，可以在启动检查配置文档里加个支持float64的开关，需要的同学只要设了就可以用float64，你觉得这样如何？

**Comment by siddontang** [comment]
现在的改动可能会比较大，接口这些的全是int的。

**Comment by insionng** [comment]
好吧 还真是个蛋疼的遗留问题  现在只能将就的转换后存储了

**Comment by siddontang** [comment]
恩，等我忙完了这一段时间，看有没有时间完全重构吧。
