### ISSUE TITLE
内存数据库LPop后内存降不下来

### ISSUE THREAD

**Issue by guonaihong** [ledisdb/ledisdb#214]
//在一个go程里不停地往ledis数据库里插入，达到一定的长底LPop数据。跑了5300秒，内存占用从最开始的324468KB 到最后的964292KB，中间一直在上涨，没有降过。

```
const (
    K_LOGS = "logs"
)

func textInsert(db *ledis.DB, val []byte, limit int) {
    c, err := db.RPush([]byte(K_LOGS), []byte(fmt.Sprintf("[%s] %s", time.Now().String(), string(val))))
    if err != nil {
        log.Fatalln("add log of ", val, " failed:", err)
    }
    if c > int64(limit) {
        if _, err := db.LPop([]byte(K_LOGS)); err != nil {
            log.Fatalln("pop log failed:", err)
        }
    }
}

func main() {
    var l *ledis.Ledis
    var db *ledis.DB
    var err error

    cfg := lediscfg.NewConfigDefault()
    cfg.DBName = goleveldb.MemDBName
    if l, err = ledis.Open(cfg); err != nil {
        log.Println("open underlying log db failed")
        log.Fatalln(err)
    }

    if db, err = l.Select(0); err != nil {
        log.Println("open underlying log db failed")
        log.Fatalln(err)
    }

    mylimit := 20000
    for i := 0; ; i++ {
        textInsert(db, []byte(fmt.Sprintf("hello %d", i)), mylimit)
    }
}
```

**Comment by siddontang** [comment]
你用的内存数据库，数据全放内存的，内存不会降的。

**Comment by jan4984** [comment]
但是有Pop掉啊。比如MySQL，有insert有delete，占用空间在一定阈值是会回收的才对。

**Comment by siddontang** [comment]
这个就要看goleveldb内部具体怎么实现的了，另外，你这个数据还不到1mb，有点小，不记得goleveldb的cache是4mb还是64mb了。

**Comment by jan4984** [comment]
神了，LPush RPop没问题，RPush LPop内存轰轰轰的涨，同样代码。
肯定哪儿有bug，我看了半天，改不来，DB太复杂了...

**Comment by siddontang** [comment]
lpush/rpush和lpop/rpop用的是同一套代码，内存涨是涨了多少？4mb，还是更多？

**Comment by jan4984** [comment]
很快就能到g级别…

**Comment by siddontang** [comment]
大概知道原因了，lpush/rpop的逻辑会重用index的head/tail seq，所以每次都是在内部用一个seq上面操作数据，但是rpush/lpop会用不同的seq，也就导致了每次都是删除老的数据，然后插入了新的数据，导致底层db一直在compaction，然后你这个测试插入太快了，根本处理不过来了，所以内存暴涨。

这个代码逻辑上面没问题，但是需要优化，但我现在没时间弄这个，只能todo，谢谢。

**Comment by jan4984** [comment]
如果我没理解错的话，好像不对。
我加了打印消息，lpush/rpop和rpush/lpop都会导致seq不停左移或右移。同时`t.Delete(itemKey)`也是跟着一直移动。也就是说head/tail/meta这3个key在两种操作下都是一直变化的，所以不是很确定你说的`index`试不是指保存list结构的这3个key。

**Comment by siddontang** [comment]
哦，所以现在我也不确定为啥会内存涨了，主要是现在没时间弄这个。
@jan4984  你能不能帮我profile一下，看内存到底消耗在什么地方？ledisdb server可以直接打开pprof，不过如果你只是test，就需要手动注入pprof的代码了。

**Comment by jan4984** [comment]
这两天又跑了几次，这个问题还不是很确定。可以确定的是Lpush/Rpop比Rpush/LPop占用内存会低很多(像这里贴的代码会多几百MB-top命令看RES)。不过，最终占用都是稳定的。所以不算是什么太大的问题吧。
