### ISSUE TITLE
how to support lmdb

### ISSUE THREAD

**Issue by sotoup** [ledisdb/ledisdb#235]
# make build_lmdb

godep go install -tags ' lmdb' ./...  
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT=1 wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
package github.com/siddontang/ledisdb/cmd/ledis-load
    imports github.com/siddontang/ledisdb/ledis
    imports github.com/siddontang/ledisdb/rpl
    imports github.com/siddontang/ledisdb/store
    imports github.com/siddontang/ledisdb/store/mdb
    imports github.com/siddontang/ledisdb/vendor/gomdb: must be imported as gomdb
godep: go exit status 1
make: **\* [build_lmdb] 错误 1

**Comment by siddontang** [comment]
LedisDB is in valid gopath? 
I don't use in go 1.6 now, why does godep not search godep path?

**Comment by sotoup** [comment]
Thanks for your reply

I found a solution

export GO15VENDOREXPERIMENT=0
make clean
make build_lmdb

**Comment by siddontang** [comment]
ok, ledisdb now doesn't support vendor, I will support it later then I can remove godeps.

**Comment by sotoup** [comment]
Although compile passed, ledisdb with lmdb don't work. 
because gomdb don't work with go1.6

error below:
cgo argument has Go pointer to Go pointer

**Comment by siddontang** [comment]
Maybe we should fire an issue to go lmdb, or can you help me solve it? 
I have not enough time now.

**Comment by siddontang** [comment]
Or you can skip LMDB now.

**Comment by sotoup** [comment]
I'm sorry I'm not familiar with golang
I had switch to go1.5

**Comment by siddontang** [comment]
Ok, I will find a time to upgrade to go 1.6.
