### ISSUE TITLE
Add comments to exported functions

### ISSUE THREAD

**Issue by nii236** [ledisdb/ledisdb#236]
Right now godoc.org contains documentation for [ledis](https://godoc.org/github.com/siddontang/ledisdb/ledis), but there are almost zero comments on hundreds of exported functions. 

It would be very helpful to have these comments as it will make the package much easier to use.

It might be a good idea to tag it as a `HELP WANTED: BEGINNERS` issue so that beginners can try their hand at open source contributions. Running a linter over the code will tell you the files that need changing. It was done with great effect at [InfluxDB](https://github.com/influxdata/influxdb/issues/4098)

**Comment by siddontang** [comment]
Thank you @nii236

**Comment by siddontang** [comment]
Now I have no time to do it, I will try to improve it later.
