### ISSUE TITLE
Problem with Godeps

### ISSUE THREAD

**Issue by tigranbs** [ledisdb/ledisdb#240]
Hi
I'm using LedisDB as a go package in my application and after making `go get github.com/siddontang/ledisdb/ledis` I got all packages which I needed to build my project, but when I've tried to build project with basic `go build example.go` I've started getting `undefined variable` errors from packages inside `Godeps/_workspace`.
After making a lot of tests and researches finally I solved issue on my local environment, I removed folder  `Godeps/_workspace` and made symlink to my `$GOPATH`

``` bash
rm -rf $GOPATH/src/github.com/siddontang/ledisdb/Godeps/_workspace
ln -s $GOPATH $GOPATH/src/github.com/siddontang/ledisdb/Godeps/_workspace
```

As I saw in `Godeps/_workspace` packages versions and packages pulled from `go get` in `$GOPATH` are not the same, and maybe in some packages there is a changes which we don't have in LedisDB Godeps.

**Comment by siddontang** [comment]
Hi @tigranbs 

Maybe ledisdb uses a lower version lib which your gopath has too, which lib? 
I will update ledisdb with new vendor feature (go 1.5+) but have no time to do it now, sorry.

**Comment by lunny** [comment]
Now we use go mod.
