### ISSUE TITLE
当前版本不再支持lmdb了吗

### ISSUE THREAD

**Issue by sotoup** [ledisdb/ledisdb#242]

**Comment by siddontang** [comment]
Go 1.6 can't compile LMDB package now,we should wait the package fixes it first or choose another proper one.

**Comment by kwojtaszek** [comment]
Isn't that proper library: https://github.com/bmatsuo/lmdb-go ? It looks like lmdb has better performance on Sorted Sets and Lists operations

**Comment by siddontang** [comment]
Cool, but I have no time to embed it now, very busy in this month. 😭
