### ISSUE TITLE
bitop 命令中按位取反有点问题

### ISSUE THREAD

**Issue by frankxieke** [ledisdb/ledisdb#247]
`if op == BitNot {
        for i := 0; i < len(value); i++ {
            value[i] ^= value[i]
        }
    }`

应该写成
`if op == BitNot {
        for i := 0; i < len(value); i++ {
            value[i] = ^value[i]
        }
    }`

**Comment by siddontang** [comment]
Thanks, can you send me a PR?

**Comment by frankxieke** [comment]
https://github.com/ledisdb/ledisdb/commit/2f7cbc730a2e48ba2bc30ec69da86503fc40acc7
