### ISSUE TITLE
atomicity guarantees

### ISSUE THREAD

**Issue by let4be** [ledisdb/ledisdb#251]
I can't find any information about the atomicity guarantees in case of failures
Are there any?

In redis it's guaranteed to have all operation perform atomically and it's easily possible to perform "transactions" via MULTI/LUA

I use ledis as a golang package in embedded mode only

**Comment by siddontang** [comment]
Hi @let4be 

Redis is single-thread, so it can easily support atomic and execute batch commands in a single step. LedisDB is multi-thread, so it can't guarantee any atomic for batch executions.
