### ISSUE TITLE
couldn't git clone ledisdb

### ISSUE THREAD

**Issue by a651694192** [ledisdb/ledisdb#255]
when I do git clone ,this happens:
![image](https://cloud.githubusercontent.com/assets/12841979/19414918/8b0938e6-938f-11e6-803a-08369ddbfc76.png)
why?

**Comment by siddontang** [comment]
don't use ssh clone, use https clone.

```
git clone https://github.com/siddontang/ledisdb.git 
```

**Comment by lunny** [comment]
Now we use go mod to manage repository.
