### ISSUE TITLE
最大数据量

### ISSUE THREAD

**Issue by a651694192** [ledisdb/ledisdb#258]
请问现在有使用ledisdb的实际项目吗？ 数据库最大支持量能达到多少呢？ 我们的数据是持续增长的，以后可能会达到1pb，请问能支持吗？

**Comment by siddontang** [comment]
铁定不支持 1PB，单机 1TB 可能就是极限了。
有人跟我说在生产环境用过，但我没细问公司。

**Comment by a651694192** [comment]
我明白啊。 不是单机啊。 ledisdb不是支持分布式集群吗？ 那1PB也不可能吗？

**Comment by a651694192** [comment]
还有当ledisdb增加节点时，会对业务有影响吗？

**Comment by siddontang** [comment]
没试过这么大集群量的，不保证能正常工作。
ledisdb + xcodis 才是集群，但现在我也没精力去维护 xcodis 了，另外，ledisdb 有人用在生产环境，但我不清楚 xcodis 有没有。

**Comment by lunny** [comment]
The limiatation is based on lebeldb and rocksdb.
