### ISSUE TITLE
What happened when out of memory?

### ISSUE THREAD

**Issue by kokizzu** [ledisdb/ledisdb#263]
Would it be error? or cold values evicted from RAM (but still there on disk)?

**Comment by siddontang** [comment]
If we meet OOM, the data is still here because backend engine (rocksdb/goleveldb) can guarantee this.

**Comment by kokizzu** [comment]
i mean, in Ledis, can we store items more than RAM capacity (like Redis Enterprise, Tarantool's VinylEngine, Aerospike device storage)? (or we can't, like Redis Community, Tarantool's MemTX, Aerospike memory-only staorage)
