### ISSUE TITLE
Best way to use ledis in client-server architecture?

### ISSUE THREAD

**Issue by kokizzu** [ledisdb/ledisdb#264]
I've tried bot redis (using `garyburd/redigo/redis` or `go-redis/redis`) and aerospike (using `aerospike/aerospike-client-go`), the operations are `INC`, `GET`, and `SET`, redis could perform about 3k-8k rps (9k when database is cleared), and aerospike about 8.3k (9k one time) rps.

I wan to try `ledisdb`, which client library (that have connection pooling) I should use redigo or is exists ledis' own client library?

**Comment by siddontang** [comment]
There is no own library, you can use any current library. I think redigo is ok too :-)
