### ISSUE TITLE
server.NewApp + ledis.Open

### ISSUE THREAD

**Issue by ascotan** [ledisdb/ledisdb#265]
It appears that if you run the http server you can't open a connection to the database. The issue is that if both server and the db connection use the same DataDir you get:

> resource temporarily unavailable

I haven't dug through the code much, however, it appears that the http server puts a lock on the datadir directory and any further attempts to get a database connection (via ledis.Open) fail due to resource contention for the data directory.

Is this the design of ledis or a bug?

In my particular case I wanted to open the http interface on a goroutine but continue to open the database for writes via another goroutine. This seems to be supported only if you are not using the same database.

**Comment by siddontang** [comment]
Seem that you use two processes to handle the same directory? If yes, it is ok because goleveldb/rocksdb can only allow one process at one time.

If not, there is a bug.

**Comment by ascotan** [comment]
same process, 2 goroutines

```
  cfg := config.NewConfigDefault()
  cfg.DataDir = "data"
  app, _ := server.NewApp(cfg)
  var wg sync.WaitGroup
   wg.Add(1)
   go func(app *server.App) {
     app.Run()
     wg.Done()
   }(app)

  led, _ := ledis.Open(cfg)
  db, _  := led.Select(0)
  db.HSet([]byte("hash"), []byte("hello"), []byte("world"))

  wg.Wait()
```

This dies on the fact that ledis.Open is attempting to open a directory that is locked by server.NewApp

**Comment by siddontang** [comment]
@ascotan 
You open two different ledis instances, and of course, this can not work. 
When you create the server, you can use server.App `Ledis()` function to get a ledis  instance.
