### ISSUE TITLE
Why use lock so large?

### ISSUE THREAD

**Issue by frankxieke** [ledisdb/ledisdb#266]
In ledis, every data structure has a lock , for example, 

> 
	kvBatch   *batch
	listBatch *batch
	hashBatch *batch
	zsetBatch *batch
	//	binBatch  *batch
	setBatch *batch
why do not use key-level lock?

**Comment by frankxieke** [comment]
in rocksdb wiki:

> Q: Is basic operations Put(), Write(), Get() and NewIterator() thread safe?

> A: Yes.

So I think key-level lock can improve throughput greatly.

**Comment by frankxieke** [comment]
I also noticed qdb,  in qdb the lock become larger. Can you give me some hints why do you desgin like this.

**Comment by siddontang** [comment]
@frankxieke 

I don't remember now, seem the lock is to guarantee the replication safety.
