### ISSUE TITLE
Are bit commands not working as expected ?

### ISSUE THREAD

**Issue by unoexperto** [ledisdb/ledisdb#271]
Sorry for asking here, but perhaps wiki is outdated.

Here are problems I'm having

~~1) Is there limit on offset in `BITPOS` ? `SETBIT is_renderable 1000025 1` followed by `BITPOS is_renderable 1 1000001` returns `EOF` but `BITPOS is_renderable 1 1000` gives correct position `(integer) 1000013`~~ Turned out it expects byte position, not bit position which is somewhat counter-intuitive since it expects bit position in GETBIT/SETBIT.

2) How do I scan in bitmap ? In **Differences from Redis** you mention `bxscan` and `bxrevscan` but LedisDB says these are unknown commands.

Thanks!

**Comment by siddontang** [comment]
@unoexperto 

Bitmap is treated as KV, you can not scan it directly. 
For scan KV, you can use `XSCAN KV SCAN cursor [MATCH pattern] [COUNT count]`
