### ISSUE TITLE
能不能在readme里明确描述一下ledis的使用场景？

### ISSUE THREAD

**Issue by wangcn** [ledisdb/ledisdb#275]
从feature里看，作为一个库嵌入到开发者应用里算一个。还有哪些情况下使用ledisdb是一个不错的选择？特别是相对redis有哪些优点，让用户在某些场景下用以替换redis。

**Comment by penuel-leo** [comment]
内存比硬盘昂贵太多

**Comment by CocaCola183** [comment]
+1

**Comment by qzqsmile** [comment]
有些疑问，存到磁盘是可以解决redis内存占用过大的问题。但存取速度是怎么解决

**Comment by lunny** [comment]
It converts random write to sequence random to resolve the speed problem!

**Comment by qzqsmile** [comment]
Thanks for your answer
