### ISSUE TITLE
Scan allocates full memory chunk

### ISSUE THREAD

**Issue by josephlewis42** [ledisdb/ledisdb#287]
The `scan` function in `ledis` [allocates an array the size of `count`](https://github.com/siddontang/ledisdb/blob/master/ledis/scan.go#L132) you pass in. Rather than `make([][]byte, 0, count)` ledis could make an empty array or a sensible minimum i.e. `make([][]byte, 0, min(count, 1024))`.

Go's append has [amortized time of roughly O(1)](https://github.com/golang/go/blob/master/src/runtime/slice.go#L82) so this shouldn't be a huge performance issue, but would help us save some space.

**Comment by siddontang** [comment]
Thanks @josephlewis42 

Can you send me a PR?
