### ISSUE TITLE
100% CPU Usage, 10s per operation time. Slow Down.

### ISSUE THREAD

**Issue by digipigeon** [ledisdb/ledisdb#307]
Hi, using rocksdb after a few hours of (mainly) lpush operations with about 2-3Kb JSON document size at about 200 ops / sec, the parent/master process locks up at 100%-200% (measuring via HTOP) utilisation and all operations from the client take 10seconds+ to complete.

A local benchmark seems to work faster (about 150 ops / second), but cpu remains high and client operations don't function correctly. This load remains continuously even after all client connections are dropped and no communication is being performed with the server.

strace on the master process shows the following
```
strace -p 28192
strace: Process 28192 attached
restart_syscall(<... resuming interrupted restart_syscall ...>) = -1 ETIMEDOUT (Connection timed out)
futex(0x13e1b90, FUTEX_WAKE, 1)         = 1
futex(0x13e16b8, FUTEX_WAIT, 0, {59, 999652182}) = -1 ETIMEDOUT (Connection timed out)
futex(0x13e1b90, FUTEX_WAKE, 1)         = 1
futex(0x13e16b8, FUTEX_WAIT, 0, {59, 999695595}) = -1 ETIMEDOUT (Connection timed out)
futex(0x13e1b90, FUTEX_WAKE, 1)         = 1
futex(0x13e16b8, FUTEX_WAIT, 0, {59, 999789402}) = -1 ETIMEDOUT (Connection timed out)
futex(0x13e1b90, FUTEX_WAKE, 1)         = 1
futex(0x13e16b8, FUTEX_WAIT, 0, {59, 999695347}) = -1 ETIMEDOUT (Connection timed out)
```

Restarting the application fixes the problem for the next 2 hours.

**Comment by siddontang** [comment]
Hi @digipigeon 

I suggest using go profile or perf to see which one costs the most CPU, or do you use `top -H` to see the CPU? I guess maybe RocksDB is compacting in the background after you insert too many items.

**Comment by digipigeon** [comment]
If I change the SET to a LPUSH (still at 150 ops / second), this problem does not happen.

**Comment by siddontang** [comment]
Hi @digipigeon 

SET and LPUSH are two different operations, and I think SET is much faster than LPUSH. I think the problem still exists for LPUSH, I will see it later.
