### ISSUE TITLE
restart out of memory with 500GB data

### ISSUE THREAD

**Issue by CocaCola183** [ledisdb/ledisdb#311]
Ledis use 100% memory (16GB) when restart with 500GB data files in data path.

After change the data path to another empty dir, ledis runs well.

Does ledis load data to memory when restart?

**Comment by siddontang** [comment]
@CocaCola183 

Ledis don't load data to memory.
Do you use RocksDB engine? Can you give me the LOG of RocksDB and ledis's log?

**Comment by CocaCola183** [comment]
@siddontang 

Engine is leveldb and there is no startup log. Do you need access log?

**Comment by siddontang** [comment]
leveldb will have a LOG in the leveldb data path.
