### ISSUE TITLE
EXISTS does not seem to work for hash maps

### ISSUE THREAD

**Issue by GlenDC** [ledisdb/ledisdb#315]
## how to reproduce

```
$ ledis-server -addr localhost:16379
```

```
$ redis-cli -p 16379
127.0.0.1:16379> HSET bar 0 foo
(integer) 1
127.0.0.1:16379> HKEYS bar
1) "0"
127.0.0.1:16379> EXISTS bar
(integer) 0
```

## expected behavior

```
127.0.0.1:16379> EXISTS bar
(integer) 1
```

For other types, such as a simple value, `EXISTS` does work correctly.

e.g. the following does work correctly:

```
$ redis-cli -p 16379
127.0.0.1:16379> SET foo bar
(integer) 1
127.0.0.1:16379> EXISTS foo
(integer) 1
```

**Comment by siddontang** [comment]
Hi @GlenDC 

We don't support exists for hash key, you should use hkeyexists instead. 

https://github.com/siddontang/ledisdb/wiki/Commands#hkeyexists-key

**Comment by GlenDC** [comment]
Sure, but why break compatibility with `redis`? Surely we could merge those 2 commands no, I don't see why they would need to be separate.

**Comment by siddontang** [comment]
@GlenDC 

For performance, if we must keep compatibility with redis to support these function, we must use another key to save the type of the data. E.g, if we want to support exists, so for a key foo, how do we know the real type? We must save a key foo -> string or foo -> hash in the backend engine. 

But as you see, saving another key in the write command can cause performance reduction especially when you only do `set key value`.

**Comment by siddontang** [comment]
But if you really want to keep compatibility, it is not hard to do. RebordDB and pika also do this, and we can support it too.
