### ISSUE TITLE
rocksdb使用Hash数据插入删除，内存不断上涨

### ISSUE THREAD

**Issue by steedyu** [ledisdb/ledisdb#322]
你好，
我使用的是rocksdb。仅使用了一个数据结构hash，一个hash中存储10个key-value键值，超过10条之后，会把第1条删除，然后加入一条新的，value的数据格式是一个json格式字符串，value的内容字符串保存在txt文件中大概是87kb。
请问，这种情景下，如何做能够让内存不停上涨的问题解决掉。

**Comment by siddontang** [comment]
你的内存用量取决于 rocksdb cache 配置的大小，需要看下超过了 rocksdb 的 cache 之后，内存还会不会一直上涨

**Comment by steedyu** [comment]
我使用如下配置启动ledisserver，然后用golang写了一个压测，发现linux操作系统ledisserver的内存不断飙升，降不下来，同时压测程序里有一个dial检测，会显示i/o timeout,从测试的样子看，我设置的这个cache大小，内容仍然还会继续上涨，涨到一段时间后，ledis-server就挂掉了。 我压测的数据结构就是hash，每个hash有10个field，每个field大小87kb。从这里看，感觉并不像cache设置过大（尝试过设置500mb，100mb，最后设置成1024），而内存仍然不断上涨。请问，这个有什么办法解决？
# LedisDB configuration

# Server listen address
addr = "0.0.0.0:6380"

# Server http listen address, set empty to disable
http_addr = "127.0.0.1:11181"

# Data store path, all ledisdb's data will be saved here
data_dir = "./var"

# Set the number of databases. You can use `select dbindex` to choose a db.
# dbindex must be in [0, databases - 1].
# Default databases is 16, maximum is 10240 now.
databases = 16

# Log server command, set empty to disable
access_log = ""

# Set slaveof to enable replication from master, empty, no replication
# Any write operations except flushall and replication will be disabled in slave mode.
slaveof = ""

# Readonly mode, slave server is always readonly even readonly = false  
# for readonly mode, only replication and flushall can write
readonly = false

# Authentication (for non-http connections). Connect, then use the AUTH command to authenticate.
# auth_password = "russellwashere"

# Choose which backend storage to use, now support:
#
#   leveldb
#   rocksdb
#   goleveldb
#   memory
#   
db_name = "goleveldb"

# If not set, use data_dir/"db_name"_data
db_path = ""

# Sync commit to disk if possible
#  0: no sync 
#  1: sync every second 
#  2: sync every commit 
db_sync_commit = 0

# enable replication or not
use_replication = false

# set connection buffer, you can increase them appropriately
# more size, more memory used
conn_read_buffer_size = 10240
conn_write_buffer_size = 10240

# if connection receives no data after n seconds, it may be dead, close 
# 0 to disable and not check 
conn_keepalive_interval = 0

# checking TTL (time to live) data every n seconds
# if you set big, the expired data may not be deleted immediately
ttl_check_interval = 1

[leveldb]
# for leveldb and goleveldb
compression = false
block_size = 32768
write_buffer_size = 67108864
cache_size = 1024
max_open_files = 1024

**Comment by siddontang** [comment]
方便提供下你的测试代码不？

也提供下你的配置文件

**Comment by steedyu** [comment]
压测的程序是是用golang 的redis驱动写的，不方便提供，涉及了，具体数据格式，基本就是hset 和hdel 数据，但是key中的filed所对应的数据大小比较大，大概value的大小是78kb字符串。开500goroutine进行压测。


配置文件内容如下：
addr = "0.0.0.0:7380"


http_addr = "127.0.0.1:11181"


data_dir = "./var"


databases = 16


access_log = ""


slaveof = ""


readonly = false


 
db_name = "goleveldb"


db_path = ""


db_sync_commit = 0


use_replication = false


conn_read_buffer_size = 10240
conn_write_buffer_size = 10240


conn_keepalive_interval = 0


ttl_check_interval = 1

[leveldb]
compression = false
block_size = 32768
write_buffer_size = 67108864
cache_size = 52428800
max_open_files = 1024

**Comment by siddontang** [comment]
你的 rocksdb 配置呢？上面贴的是 leveldb 的
内存涨到多少？

**Comment by steedyu** [comment]
leveldb，我最后用leveldb测试也是同样的情况，这里就给出了leveldb的配置，一样的情况。

**Comment by siddontang** [comment]
> 压测的程序是是用golang 的redis驱动写的，不方便提供，涉及了，具体数据格式，基本就是hset 和hdel 数据，但是key中的filed所对应的数据大小比较大，大概value的大小是78kb字符串。开500goroutine进行压测。

你如果发现内存一直上涨，然后停掉测试代码，内存会不会降下来，你这个数据量太大，很可能 GC 忙不过来
你可以在启动 ledis server 的时候传入  --pprof=true，然后看看 curl http://ip:6060/debug/pprof/heap ，这样就能知道具体的 heap 情况
