### ISSUE TITLE
使用package代码写入不了ledisdb

### ISSUE THREAD

**Issue by steedyu** [ledisdb/ledisdb#323]
服务端：运行在内网中一台机器
       ledis-server -addr "0.0.0.0:7380'

客户端代码：
        cfg := lediscfg.NewConfigDefault()
	cfg.Addr = "xxx.xxx.xxx.xxx:7380"	//xxx.xxx.xxx.xxx 内网某台机器ip地址
	l, err := ledis.Open(cfg)
	db, err1 := l.Select(0)
	fmt.Println(err1)

	db.Set([]byte("setkey"),[]byte("1"))
	r, err2 := db.HSet([]byte(“hashkey”), []byte("f1"), data)
	fmt.Println(r,err2)

然后使用redis-cli去获取数据，没有写入任何数据；看过客户端代码的返回r是0。debug源代码，也未有明确发现，err都是nil。请问下这是什么问题？

**Comment by siddontang** [comment]
你 redis cli 如何获取数据的？

**Comment by steedyu** [comment]
redis cli就是直接 redis-cli -h xxxx.xxx.xx.xxx -p 7380

**Comment by siddontang** [comment]
在 redis cli 里面具体命令

**Comment by steedyu** [comment]
hgetall hashkey

**Comment by siddontang** [comment]
get setkey 呢？

**Comment by steedyu** [comment]
get setkey也是获取不到

**Comment by siddontang** [comment]
客户端代码：
cfg := lediscfg.NewConfigDefault()
cfg.Addr = "xxx.xxx.xxx.xxx:7380"	//xxx.xxx.xxx.xxx 内网某台机器ip地址
l, err := ledis.Open(cfg)
db, err1 := l.Select(0)
fmt.Println(err1)

你为啥直接 ledis open 而不是用的一般的 redis client？ ledis open 会打开一个本地的 db，跟你的远端没啥关系。

你直接 redis-cli 连上去，set 一下，看能不能 get

**Comment by lunny** [comment]
Closed as expired.
