### ISSUE TITLE
build_leveldb.sh有问题

### ISSUE THREAD

**Issue by csjc008** [ledisdb/ledisdb#332]
请将leveldb的git链接改为https, 对于没有ssh key的才可以build.
leveldb.patch位于tools目录下, 
并且libleveldb.* 编译后位于 out-static 和 out-shared子目录下, 在脚本中指定的位置上并没有.

**Comment by siddontang** [comment]
Thanks @csjc008 
Please send me a PR to fix it.

**Comment by FanyuxiNIE** [comment]
能否打一份正确的build文件
