### ISSUE TITLE
 FAIL: TestStore

### ISSUE THREAD

**Issue by Charleslvn** [ledisdb/ledisdb#334]
Testing: "/builddir/build/BUILD/ledisdb-0.6/_build/src/github.com/siddontang/ledisdb/store"
+ GOPATH=/builddir/build/BUILD/ledisdb-0.6/_build:/usr/share/gocode
With:
go 1.9.4 x86_64
github.com/siddontang/ledisdb 0. 6

 Hello,
 I try to build and test your project and it fails with :

> 
> + go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
> # testmain
> warning: unable to find runtime/cgo.a
> --- FAIL: TestStore (0.00s)
>         store_test.go:21: store goleveldb
>         store_test.go:367: [{[97] [49]} {[98] []} {[99] []}] != [{[97] [49]} {[98] []} {[99] []}]
> FAIL
> exit status 1
> FAIL    github.com/siddontang/ledisdb/store     0.007s
> 
> 

Could you help me please ?

Thanks

**Comment by siddontang** [comment]
oh, do you use `make test` to build it?

**Comment by lunny** [comment]
Since the CI now PASS, please let me know what did you do.
