### ISSUE TITLE
SMembers not consistent between replicated databases

### ISSUE THREAD

**Issue by mstory21** [ledisdb/ledisdb#344]
My master database has this:

[centos@matt4 run3]$ sudo docker exec -it 8b0a6b54771b redis-cli -p 6382 smembers 00000019-Tags
 1) "$$BankId"
 2) "$$CVV"
 3) "$$ClientSecret"
 4) "$$DrugName"
 5) "$$PIN"
 6) "$$SSN"
 7) "$$Tag0"
 8) "$$Tag1"
 9) "$$Tag2"
10) "$$Tag3"
11) "$$Tag4"
12) "$$Tag5"
13) "$$Tag6"
14) "$$Tag7"
15) "$$Tag8"
16) "$$Tag9"
[centos@matt4 run3]$ sudo docker exec -it 8b0a6b54771b redis-cli -p 6382 role
1) "master"
2) (integer) 20031901
3) 1) 1) "10.0.0.31"
      2) "6382"
      3) "20031901"

My slave database has this:
[centos@matt3 ~]$ sudo docker exec -it e9869330062b redis-cli -p 6382 smembers 00000019-Tags
1) "$$BankId"
2) "$$ClientSecret"
3) "$$DrugName"
4) "$$PIN"
5) "$$SSN"
[centos@matt3 ~]$ sudo docker exec -it e9869330062b redis-cli -p 6382 role
1) "slave"
2) "10.0.0.30"
3) (integer) 6382
4) "connected"
5) (integer) 20031901

These need to be consistent or sets are unusable.  Using Ledis linked with RocksDB.

**Comment by siddontang** [comment]
oh, does the slave fall behind the master?  Every time you insert a member, the slave can't see it?

**Comment by mstory21** [comment]
I believe at some point the databases became inconsistent, perhaps on the key that counts how many members are in the set.  I was doing a lot of failover testing at the time.  So this could be related to replication.

**Comment by siddontang** [comment]
hi @mstory21 

Do you mean that the data can be eventually consistent? If yes, seem this the problem of the speed of async replication, and it certainly exists. Maybe we should think how to speed up it.
