### ISSUE TITLE
How do you scan the whole db collection?

### ISSUE THREAD

**Issue by Xeoncross** [ledisdb/ledisdb#347]
I am trying to understand how to use the 'Scan' commands to iterate over an entire database. Is something like this correct?

	var v [][]byte
	types := []ledis.DataType{ledis.KV, ledis.LIST, ledis.HASH, ledis.SET}

    loop:
	for _, keyType := range types {
		var cursor []byte
		for {

			if v, err = db.Scan(keyType, cursor, 3, false, ""); err != nil {
				break loop
			}

			if len(v) == 0 {
				break
			}

			fmt.Printf("%#v => %q\n", v, v)

			cursor = v[len(v)-1:][0]
		}
	}

**Comment by justinfx** [comment]
This was a helpful example. Thanks :-)

**Comment by lunny** [comment]
I think it's right. @siddontang
