### ISSUE TITLE
Recomended way to store latitude / longitude / geo cordinates? 

### ISSUE THREAD

**Issue by Xeoncross** [ledisdb/ledisdb#348]
I would like to index objects by their latitude / longitude for searching. So far the best I've come up with is to create `360 * 360 = 129,600` sets for each latitude and longitude degree. Then UNION
the sets covering the 1x1, 2x2, 3x3, etc.. grid of area you want. (`3x3` would be a 180 mile square)

Degrees of latitude are parallel so the distance between each degree remains
almost constant but since degrees of longitude are farthest apart at the equator
and converge at the poles, their distance varies greatly.

Each degree of latitude is approximately 69 miles (111 kilometers) apart. A degree of longitude is widest at the equator at 69.172 miles (111.321) and gradually shrinks to zero at the poles.

    SADD lat:32:lng:96 "Dallas"
    SADD lat:32:lng:97 "Fort Worth"
    SUNION lat:32:lng:96 lat:32:lng:97 lat:32:lng:98
           lat:33:lng:96 lat:33:lng:97 lat:33:lng:98
           lat:34:lng:96 lat:34:lng:97 lat:34:lng:98

If 69 miles is too big, I could break down the latitude/longitude into tenths so we can search by tighter areas (69 miles / 0.1 = 6.9 miles).

    (360 * 10) * (360 * 10) = 12,960,000 buckets

    // Lat:32.7766642, Lng:-96.79698789
    SADD lat:327:lng:967 "Dallas"

_Note: instead of storing names I would store ids_

### Is this the best approach to lookups?

**Comment by siddontang** [comment]
Hi @Xeoncross 

Sorry for the late reply, I am very busy these days.

Your case is very interesting, I have never thought about it. Using Sets is a way, or maybe we can use Lists, E.g.:

```
lat:32 -> lng list
lat:33 -> lng list
```

You can use 360 items or more in one list. Each item represents one longitude. E.g, the first item is lng:-180, ... lng:0, ... lng:180

So if you want to search an area, you can call Redis List `LRANGE` for each latitude.

**Comment by Xeoncross** [comment]
Did you suggest lists because they take up less space or are faster for lookups?

Are you saying each item in the list is an object that contains all keys for the actual objects in that longitude? I don't understand how lists would work since lists are 0 indexed so the list would have to be 

    lat:32 -> list [
        0: {34, 521, 94, ...}, 
        1: {...}, 
        ..., 
        360: {..}
    ]

**Comment by ivanjaros** [comment]
usually, geolocation is stored in form of geohash in uint64 form, not in floats. See https://github.com/mmcloughlin/geohash#func--encodeintwithprecision
