### ISSUE TITLE
ledisdb.com has expired

### ISSUE THREAD

**Issue by laverya** [ledisdb/ledisdb#350]
As can be seen by visiting [ledisdb.com](http://ledisdb.com/?reqp=1&reqr=), the registration has expired.

![image](https://user-images.githubusercontent.com/2318911/43280216-12b56baa-90c5-11e8-9941-c09eb786df3c.png)

**Comment by siddontang** [comment]
oh, forget to renew 😭

**Comment by lunny** [comment]
Now it's https://ledisdb.io .
