### ISSUE TITLE
I want to use the ranking system.

### ISSUE THREAD

**Issue by dev-shinyu** [ledisdb/ledisdb#361]
Dear Siddontang

I used redis as a ranking collection function only.

It was very easy to implement using the api of go-leaderboard git

https://github.com/dayvson/go-leaderboard

I'd like to migrate to high-performance ledis to overcome the limitations of redis memory

Is there a simple way to migrate to the ledis?

I checked out that the redis command used in the go-leaderboard project was supported by the ledis.

I just want to have a quick and easy migration method as much as possible because I lack my experience and lack of project schedule.

Please give me advice.

And can you tell me how to migrate data from redis to ledis? :)

thank you!

dev.shinyu@gmail.com

**Comment by lunny** [comment]
I think you can migrate redis data to ledis.
