### ISSUE TITLE
Ledisdb keyspace notification support

### ISSUE THREAD

**Issue by popadi** [ledisdb/ledisdb#365]
Hello!

I was wondering if ledisdb has a keyspace notifications feature as Redis does [1] or any other mechanism that I am able to use to simulate a callback when a specific event occurs. In my use-case for example, most of the keys expire after 24h and I'd like to run a callback function when this happens (I'd like to subscribe somehow to these events).

I tried [this](https://medium.com/@micah1powell/using-redis-keyspace-notifications-for-a-reminder-service-with-node-c05047befec3) code (which is for Redis, I know) but I am getting a lot of errors like:

```
(node:20210) UnhandledPromiseRejectionWarning: ReplyError: command not found
    at parseError (/home/adrianpop/karma-agents/karma-redis-notification-lib/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/adrianpop/karma-agents/karma-redis-notification-lib/node_modules/redis-parser/lib/parser.js:302:14)
(node:20210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

So, does ledisdb support this? If not, is it something that will be implemented in the future?
Thanks!

[1] https://redis.io/topics/notifications

**Comment by siddontang** [comment]
Sorry @popadi 

Now we haven't supported this feature, and it is not in the plan because I am too busy. 😭

**Comment by popadi** [comment]
Okay, thanks for the answer!
