### ISSUE TITLE
DBSIZE

### ISSUE THREAD

**Issue by robert-zaremba** [ledisdb/ledisdb#72]
This command is missing.
http://redis.io/commands/dbsize

**Comment by wenerme** [comment]
How ledis strong consensus replication ?

**Comment by siddontang** [comment]
@wenerme 

we use xcodis(a modified codis version) to support cluster, so we will not consider replication using raft or paxos any longer.
Ledisdb support a sync replication (master <-> slave) in configuration. but it will degrade to asynchronous replication sometimes, so not always consensus.
